# Generated by Django 4.0.4 on 2022-05-31 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_student_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='school',
            field=models.IntegerField(),
        ),
    ]
